inventory=Inventory()
# adding items to the cart
inventory.add_to_cart("banana", 2)
inventory.add_to_cart("apples", 4)
inventory.add_to_cart("carrots", 10)
inventory.add_to_cart("cabbages", 5)
inventory.add_to_cart("spinach", 2)
inventory.add_to_cart("lemons", 4)
inventory.add_to_cart("garlic", 10)
inventory.add_to_cart("mangoes", 5)
