#Update  the inventory
inventory.add_to_inventory("cucumbers", 5)
inventory.add_to_inventory("sukuma wiki", 10)
inventory.add_to_inventory("onions", 5)
inventory.add_to_inventory("brocolli", 10)
inventory.add_to_inventory("apples", 5)
inventory.add_to_inventory("strawberries", 10)
inventory.add_to_inventory("carrots", 5)
inventory.add_to_inventory("pineapples", 10)
inventory.add_to_inventory("dodo", 5)
inventory.add_to_inventory("lemons", 10)
